field: [
  "CV",
  "NLP",
]

method: [
  "Unsupervised Learning",
]

data: [
  "RGB Image",
  "Depth Image",
  "Intensity Image",
  "Point Cloud",
  "Mesh",
  "Video"
]

task: [
  "Classification",
  "Detection",
  "Depth Estimation",
  "Novel View Synthesis",
  "Panoptic Segmentation",
  "Part Segmentation",
  "Pose Estimation",
  "Semantic Segmentation",
  "Object Generation",
  "Scene Generation",
  "Texture Generation"
]

etc: [
  "Multi-View",
]
